version: 0.0
os: linux
files:
  - source: /
    destination: /StDigital
resources:
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh  
  ApplicationStop:
    - location: scripts/kill-server.sh
  ApplicationStart:
    - location: scripts/start-server.sh
      runas: ec2-user